RETRIEVER_PROFILES = {
    "TRADITIONAL": """
        "Multi-factor authentication bypass mitigation strategies",
        "Cryogenic valve calibration tolerances",
        "Amortization rules for intangible assets",
        "Post-operative care protocols for joint replacement",
        "Data retention limits for biometric identifiers",
        "Subsurface geological mapping techniques",
        "Student data privacy compliance requirements",
        "Supply chain vulnerability assessment framework",
        "Turbine blade stress fracture indicators",
        "Wholesale inventory turnover optimization models",
        "How does a stateless firewall handle packet inspection differently than a stateful one?",
        "What are the indicators of compromise for a zero-day exploit targeting network attached storage?",
        "What is the recommended patch management cycle for critical infrastructure servers?",
        "How do API gateways manage rate limiting and throttling for external endpoints?",
        "What steps are required to implement zero-trust architecture in a hybrid cloud environment?",
        "How do you configure an automated failover for a distributed database cluster?",
        "What are the security risks associated with container escape vulnerabilities?",
        "How does a public key infrastructure validate revoked certificates?",
        "What is the function of a security information and event management system during a DDoS attack?",
        "How can developers prevent SQL injection vulnerabilities in legacy web applications?",
        "What are the primary clinical indications for prescribing broad-spectrum antibiotics?",
        "How does the blood-brain barrier restrict the delivery of therapeutic peptides?",
        "What are the environmental impacts of nitrogen runoff from agricultural fertilizers?",
        "How do scientists measure the isotopic composition of ice core samples?",
        "What is the mechanism of action for competitive enzyme inhibitors?",
        "How do changes in ocean temperature affect coral reef calcification rates?",
        "What protocols should be followed when handling biohazardous waste in a level 3 laboratory?",
        "How does a mass spectrometer identify unknown chemical compounds?",
        "What are the diagnostic criteria for early-stage neurodegenerative diseases?",
        "How do mRNA vaccines stimulate an immune response in human cells?",
        "How do central banks use open market operations to control inflation?",
        "What is the difference between a direct and an indirect cash flow statement?",
        "How do insurance companies calculate the risk premium for commercial property coverage?",
        "What are the tax implications of a corporate spin-off for retail investors?",
        "How does a hedge fund utilize pairs trading as a market-neutral strategy?",
        "What factors influence the credit rating downgrade of a sovereign bond?",
        "How do actuary tables forecast life expectancy for annuity pricing?",
        "What is the process for filing a business interruption insurance claim?",
        "How do interest rate swaps mitigate variable rate risk for long-term debt?",
        "What are the reporting requirements for suspicious activity reports in banking?",
        "What are the legal requirements for establishing a chain of custody for physical evidence?",
        "How does the principle of sovereign immunity protect government officials from civil liability?",
        "What criteria do regulatory agencies use to evaluate environmental impact statements?",
        "How does a public utility commission determine fair electricity pricing structures?",
        "What are the statutory definitions of intellectual property infringement under international trade law?",
        "How does the freedom of information act apply to internal government memos?",
        "What steps must a municipality take to approve a zoning variance for commercial development?",
        "How do courts interpret the enforceability of non-compete clauses in employment contracts?",
        "What are the compliance mandates for accessibility under federal disability legislation?",
        "How does a legislative body conduct oversight investigations into agency spending?",
        "How do manufacturing plants implement predictive maintenance schedules for robotic assembly lines?",
        "What are the safety standards for operating high-voltage electrical switchgear?",
        "How does a lean management system reduce waste in a continuous production process?",
        "What are the standard operating procedures for responding to a hazardous material spill?",
        "How do energy grids integrate variable renewable energy sources without losing stability?",
        "What are the documentation requirements for onboarding remote contractors in an enterprise setting?",
        "How does an organization conduct a comprehensive internal audit of its procurement processes?",
        "What parameters determine the structural integrity of composite materials in aerospace manufacturing?",
        "How do oil refineries monitor and control emissions during the cracking process?",
        "What are the industry best practices for managing employee performance evaluation records?",
        "Our development team is migrating from a monolithic architecture to microservices. We are experiencing high latency during inter-service communication. What are the proven strategies for optimizing network transport and serialization protocols to resolve this?",
        "A recent security audit revealed several unauthorized access attempts via stale user accounts. We need to implement an automated lifecycle management system. What are the standard procedures for identifying and deprovisioning inactive identities across enterprise directories?",
        "The IT department is planning a disaster recovery drill for our primary data center. We need to minimize our recovery time objective for critical transaction logs. What replication configurations are recommended for synchronous data mirroring over long distances?",
        "We are deploying an automated code analysis tool in our continuous integration pipeline. The tool is flagging a high volume of false positives related to cryptographic operations. How can we tune the static analysis rules to filter out irrelevant warnings without missing actual vulnerabilities?",
        "Users are reporting intermittent connection drops when accessing our cloud-based application from mobile devices. The network logs indicate packet loss at the edge routing layer. What diagnostic steps should network engineers take to isolate the root cause of this routing instability?",
        "Our security operations center detected a potential data exfiltration event involving large encrypted payloads sent to an external IP address. We need to conduct a forensic analysis on the compromised host machine. What specific memory artifacts and network connection states should we extract first?",
        "We are upgrading our legacy encryption protocols across all internal web servers to meet new compliance mandates. Some legacy client applications may not support the newer cipher suites. How can we implement a phased deprecation plan that maintains security while minimizing service disruption for older clients?",
        "The database administration team is reporting high CPU utilization caused by complex analytical queries running concurrently with transactional workloads. What partitioning and indexing strategies can we apply to isolate read-heavy reporting from write-heavy operations?",
        "An external vendor requires access to our internal project management system to collaborate on a new software release. We need to enforce least-privilege access controls. What methods should we use to restrict their permissions to only specific repositories and issue boards?",
        "Our web application is experiencing an influx of automated scraping bots that bypass traditional CAPTCHA challenges. This is causing significant resource exhaustion on the origin servers. What behavior-based rate-limiting strategies can we implement at the reverse proxy layer to mitigate this?",
        "A research team is investigating the degradation rate of biodegradable polymers under marine conditions. The initial findings show highly variable breakdown times depending on water depth. What environmental variables and microbial populations should be analyzed to explain these discrepancies?",
        "A clinical trial is evaluating the efficacy of a new monoclonal antibody for treating autoimmune disorders. Several participants have developed unexpected adverse reactions during the escalation phase. What standard reporting protocols must the principal investigator follow to notify the safety monitoring board?",
        "We are designing a laboratory study to test the thermal conductivity of newly synthesized graphene composites. The measurement apparatus is susceptible to ambient temperature fluctuations. How can we calibrate the thermal sensors and isolate the testing environment to ensure reproducible data?",
        "A public health department is investigating a localized outbreak of a waterborne pathogen in a rural community. The source of the contamination has not been identified. What epidemiological tracing methods and water sampling strategies should be deployed to locate the origin of the infection?",
        "Our genetics laboratory is analyzing high-throughput sequencing data to identify rare variants associated with metabolic syndromes. The current filtering pipeline is generating a large number of candidate genes. What bioinformatic criteria should we use to prioritize variants for functional validation studies?",
        "A study on urban heat islands requires the integration of satellite thermal imagery with ground-level meteorological data. The spatial resolutions of the datasets do not match. What resampling techniques and statistical downscaling models are recommended to align these data layers accurately?",
        "A hospital administration team wants to reduce patient readmission rates for chronic heart failure within thirty days of discharge. The current transition-of-care plan relies on self-reported patient metrics. What structured follow-up protocols and clinical interventions have proven most effective in lowering these readmissions?",
        "An agricultural research station is developing drought-resistant crop varieties through selective breeding programs. The test plots are experiencing unpredictable weather patterns. How should the researchers design the experimental layout to control for spatial soil heterogeneity and microclimate variations?",
        "We are reviewing historical climate data to model the impact of rising sea levels on coastal wetlands. The historical records contain missing data points over several decades. What data imputation methods are considered scientifically rigorous for reconstructing continuous environmental timelines?",
        "A pharmacological study needs to determine the bioavailability of an oral drug formulation in pediatric populations. Ethical constraints limit the number of blood samples that can be collected from each subject. What sparse sampling designs and population pharmacokinetic modeling techniques can overcome this limitation?",
        "An investment firm is reviewing its portfolio exposure to sudden commodity price shocks in the energy sector. The current risk models assume a normal distribution of market returns. What stress-testing methodologies and historical scenario analyses should be implemented to capture tail-risk events more accurately?",
        "Our corporate legal department is drafting a joint venture agreement with an international partner. The contract involves cross-border transfer of proprietary technology. What specific clauses regarding dispute resolution, governing law, and export control compliance must be included to protect our intellectual property?",
        "A government agency is updating its procurement guidelines for infrastructure projects funded by public-private partnerships. There are concerns about cost overruns and project delays. What performance-based contracting mechanisms and risk-sharing structures should be incorporated into the new guidelines?",
        "An insurance company is revising its underwriting guidelines for commercial cyber liability policies due to an increase in ransomware claims. The current assessment forms lack depth regarding network security controls. What specific technical controls and incident response capabilities should the underwriters evaluate before issuing a policy?",
        "A compliance officer is auditing the trade execution logs of an investment bank to detect potential market manipulation or front-running. The volume of daily transactions is too large for manual review. What algorithmic pattern-matching techniques can be used to identify anomalous trading behaviors that warrant further investigation?",
        "A non-profit organization is applying for a government grant to fund a community development program. The grant application requires a detailed logic model and measurable performance indicators. How should the organization structure its evaluation framework to demonstrate a direct causal link between program activities and long-term community outcomes?",
        "Our legal team is preparing for a regulatory audit regarding consumer data privacy practices. We need to verify that our data mapping processes align with current state-level transparency mandates. What documentation must we provide to demonstrate that consumers can successfully opt out of data sharing?",
        "An enterprise is restructuring its debt obligations by replacing short-term high-interest notes with long-term commercial bonds. The market is experiencing high volatility. What factors should the chief financial officer consider when timing the bond issuance to minimize the cost of capital and underwriting fees?",
        "A municipal government wants to implement a progressive property tax incentive program to encourage the development of affordable housing units. What legal and economic frameworks should the city council review to ensure the program complies with state constitutional uniformity clauses?",
        "An internal audit team is reviewing the expense reimbursement reports of senior executives over the past fiscal year. Several line items lack itemized receipts or business purpose documentation. What corrective actions and compliance enforcement protocols should the audit committee recommend to prevent future policy violations?",
        "A manufacturing plant is experiencing high rejection rates for precision-machined components due to microscopic surface defects. The quality control team suspects variation in the cooling fluid temperature during the milling process. How can we set up a real-time monitoring loop to correlate fluid temperature with surface roughness measurements?",
        "An energy company is decommissioning an offshore drilling platform and must restore the marine environment to its original state. The regulatory framework requires a comprehensive closure plan. What engineering methods and environmental mitigation strategies are standard practice for safely plugging wells and removing subsea structures?",
        "A retail chain is expanding its online marketplace to allow third-party sellers to list products directly on its platform. This expansion has led to an increase in counterfeit product complaints from consumers. What automated verification processes and seller vetting protocols should the platform implement to mitigate this risk?",
        "A logistics provider is optimizing its fleet routing to reduce fuel consumption and carbon emissions across a multi-state distribution network. The current software does not account for real-time traffic anomalies or changing weather conditions. What dynamic routing algorithms and data integration methods should be evaluated?",
        "A chemical manufacturing facility needs to upgrade its emergency relief systems to handle potential runaway exothermic reactions. The original design calculations are outdated due to changes in chemical formulations. What thermodynamic modeling approaches should engineers use to resize the pressure safety valves safely?",
        "A commercial real estate management firm wants to improve the energy efficiency of its portfolio by installing smart building automation systems. The buildings vary significantly in age and existing infrastructure. What baseline energy auditing procedures should be conducted to prioritize buildings for the upgrade?",
        "A retail apparel brand is facing significant inventory stockouts for popular seasonal items due to forecasting inaccuracies in the supply chain. The historical sales data is distorted by pandemic-related store closures. What demand forecasting models can effectively smooth out these historical anomalies to project future demand?",
        "An electrical utility is experiencing accelerated degradation of underground distribution cables in coastal areas with high soil salinity. The maintenance team needs to predict cable failures before they cause widespread outages. What non-destructive testing methods and diagnostic indicators can assess cable insulation health?",
        "A food processing company is upgrading its sanitation protocols to prevent cross-contamination of common allergens on shared production lines. The current cleaning validation relies on visual inspections. What analytical testing methods and verification procedures should be introduced to confirm the complete removal of allergen residues?",
        "An enterprise warehouse operation wants to introduce autonomous mobile robots to assist with order picking and sorting. The current warehouse layout features narrow aisles and high-traffic pedestrian zones. What safety protocols and spatial mapping technologies must the robots utilize to operate safely alongside human workers?"
    """,

"HYBRID": """   
"what is the latest performance data on the new renewable energy grid architecture and how does it compare to 2024 benchmarks",
"find all documentation regarding current cyber threat intelligence reporting protocols and specific incident response workflows for high-severity vulnerabilities",
"summarize the regulatory requirements for cross-border financial transactions and provide the relevant policy excerpts for compliance auditing",
"how do deep learning optimization techniques impact real-time signal processing in satellite communications",
"locate the current standard operating procedures for handling hazardous material spills in manufacturing environments including containment and reporting mandates",
"explain the correlation between market volatility indices and interest rate adjustments in emerging economies during the last fiscal quarter",
"find academic research on CRISPR-Cas9 advancements and the associated ethical frameworks for clinical application",
"what are the architectural specifications for the new cloud-native microservices infrastructure as defined in the technical requirements document",
"provide a detailed comparison of existing encryption standards for securing sensitive client data in transit across public networks",
"identify the key factors influencing patient readmission rates in hospitals and list the evidence-based intervention strategies",
"how does the current tax legislation impact small business deductions for remote work expenses",
"retrieve information on the historical performance of carbon capture technologies and the projected efficiency gains for industrial-scale deployment",
"what are the core principles of zero-trust security architecture and how should they be implemented in a hybrid enterprise environment",
"provide an overview of the legal implications of automated decision-making systems in government hiring processes",
"compare the energy density and cycle life of next-generation solid-state batteries versus traditional lithium-ion solutions",
"list the required documentation for international trade compliance involving dual-use technology exports",
"what are the primary drivers of supply chain disruption in the semiconductor industry and what mitigation strategies have been documented",
"explain the methodology for conducting longitudinal studies on public health trends and the statistical tools recommended for data validation",
"find the latest white paper on machine learning model interpretability and its relevance to high-stakes decision support systems",
"what are the guidelines for handling personally identifiable information under global data protection regulations",
"analyze the technical challenges of integrating legacy mainframes with modern API-driven application architectures",
"how do adaptive learning platforms improve student engagement in STEM courses at the university level",
"retrieve the specific engineering tolerances for structural steel components used in high-seismic zone construction",
"what are the current best practices for mitigating cross-site scripting attacks in web-based enterprise applications",
"provide a summary of recent advancements in quantum error correction and their practical implications for cryptographic systems",
"how does inflation affect the long-term investment strategies for diversified retirement portfolios",
"list the specific safety protocols for operating autonomous heavy machinery in open-pit mining environments",
"what is the regulatory status of decentralized finance protocols in major jurisdictions and what are the primary compliance risks",
"explain the chemical composition differences between synthetic lubricants and bio-based alternatives for industrial mechanical systems",
"find documentation on the network latency requirements for real-time remote robotic surgery",
"what are the recommended mitigation strategies for insider threats in high-security research facilities",
"summarize the environmental impact assessment reports regarding recent offshore wind farm developments",
"how can organizations effectively manage technical debt while maintaining rapid feature delivery cycles",
"what are the mandatory security controls for cloud service providers handling government contract data",
"compare the effectiveness of different wastewater treatment technologies in removing emerging contaminants like microplastics",
"retrieve the policy regarding employee remote access to internal intellectual property repositories",
"what is the relationship between atmospheric carbon concentration and extreme weather event frequency as documented in recent climate studies",
"how do central bank digital currencies influence traditional banking liquidity and settlement processes",
"find the technical specifications for implementing identity and access management federation across disparate cloud environments",
"what are the legal requirements for disclosure of intellectual property ownership in joint research ventures",
"provide a guide on optimizing serverless function performance for high-concurrency event-driven architectures",
"what are the key performance indicators for assessing the success of digital transformation initiatives in the manufacturing sector",
"explain the impact of recent maritime law updates on international shipping routes and cargo insurance premiums",
"how can deep neural networks be applied to detect anomalies in industrial IoT sensor data",
"retrieve the standard laboratory protocols for handling BSL-3 level pathogens",
"what are the current trends in sustainable urban planning and the role of smart transportation systems",
"list the technical considerations for migrating on-premises databases to multi-region cloud storage solutions",
"how do changes in global interest rates influence the valuation of long-term infrastructure projects",
"what are the established guidelines for conducting rigorous peer reviews of clinical drug trial results",
"provide an analysis of the interoperability challenges between competing blockchain protocols in enterprise supply chains",
"what are the physical constraints of miniaturized satellite antennas in CubeSat designs",
"how can machine learning be used to predict hardware component failure in data center cooling systems",
"retrieve the compliance requirements for handling health insurance information under standardized industry regulations",
"what are the security vulnerabilities associated with improperly configured container orchestration platforms",
"summarize the current state of fusion energy research and the technological hurdles to commercialization",
"how do fiscal policy changes impact the long-term viability of renewable energy subsidies",
"what are the best practices for documenting architectural design decisions in large-scale software development teams",
"find information on the social impact of automation in rural industrial communities",
"what are the specific requirements for fire suppression systems in high-density server rooms",
"explain the role of public-private partnerships in funding large-scale national infrastructure projects",
"how does exposure to ultraviolet radiation affect the structural integrity of composite materials used in aerospace",
"retrieve the latest guidelines on cybersecurity risk management for utility infrastructure operators",
"what are the ethical considerations in the deployment of facial recognition technology by local law enforcement",
"provide a technical comparison of relational versus NoSQL database performance for high-velocity data ingestion",
"what are the standard methods for verifying the authenticity of digital signatures in legal documents",
"how do extreme temperature fluctuations influence the performance of power distribution transformers",
"list the diagnostic criteria for identifying early-stage neurodegenerative disorders using neuroimaging data",
"what is the historical context of trade tariff impacts on the domestic automotive manufacturing supply chain",
"explain the concept of model poisoning in federated learning environments and potential defense mechanisms",
"find documentation regarding the certification process for commercial drone operators in restricted airspaces",
"how can businesses balance operational transparency with trade secret protection in competitive markets",
"what are the performance implications of synchronous versus asynchronous replication in global database clusters",
"summarize the findings on the effectiveness of non-pharmaceutical interventions in controlling regional disease outbreaks",
"what are the requirements for data residency and sovereignty in the context of international cloud service agreements",
"how do high-frequency trading algorithms respond to sudden liquidity crunches in equity markets",
"retrieve the specifications for vibration damping materials used in precision manufacturing equipment",
"what are the current industry standards for securing remote telemetry data in the oil and gas sector",
"provide a detailed overview of the fiscal impact of corporate tax inversion strategies",
"how can reinforcement learning be optimized for energy management in smart building automation",
"what are the legal challenges associated with enforcing copyright on AI-generated creative works",
"find the latest research on the application of nanotechnology in high-efficiency solar cells",
"what are the security implications of utilizing open-source libraries with unpatched vulnerabilities in enterprise software",
"explain the methodology for stress-testing national financial systems against hypothetical economic crises",
"how do government incentive programs influence the adoption rate of electric vehicle charging infrastructure",
"retrieve the safety protocols for handling pressurized hydrogen storage tanks in industrial facilities",
"what are the primary factors contributing to the decline in biodiversity in managed agricultural ecosystems",
"list the best practices for managing secret and credential rotation in automated CI/CD pipelines",
"how does the implementation of standardized electronic health records improve continuity of care across medical specialties",
"what are the architectural requirements for high-availability database clusters in hybrid cloud environments",
"provide a summary of international treaties regarding the militarization of outer space",
"what are the technical trade-offs between centralized and edge computing for real-time video analytics",
"explain the impact of demographic shifts on the solvency of public pension systems",
"how do seismic isolation systems protect critical infrastructure components during major earthquake events",
"retrieve the guidelines for performing internal audits of compliance with anti-money laundering regulations",
"what are the current developments in synthetic biology for the production of sustainable materials",
"how can organizations automate the detection of policy violations in cloud storage buckets",
"what are the risks associated with the use of third-party APIs in critical financial infrastructure",
"summarize the technical challenges of developing long-range autonomous underwater vehicles for oceanic research",
"what are the recommended methods for data sanitization prior to disposing of enterprise storage media",
"identify the key drivers of institutional investment in green bonds" """,

"PAGEINDEX": """
"where is the table of contents located in the global security policy manual",
"find the exact page that details the compliance checklist for chapter 4",
"index of financial definitions at the back of the annual report",
"what page contains the wiring diagram for the backup power generator system",
"look up the troubleshooting flowchart for network timeouts on page 42",
"i need to find the appendix that lists all chemical formulas used in the lab manual, what page does it start on",
"where in the employee handbook is the section discussing parental leave policies and eligibility requirements",
"page number for the architectural schematic of the main data center building",
"find the glossary page for cybersecurity terminology in this textbook",
"where can I find the specific page that details the warranty exemptions for manufacturing equipment",
"can you locate the exact page in the clinical trial protocol that details adverse event reporting timelines",
"index of legal terms and statutory citations used in the merger agreement",
"what page contains the list of figures for the climate assessment report",
"find the page showing the configuration matrix for the enterprise firewall migration",
"where is the subject index in the medical billing reference guide",
"look up the page location for the hardware installation steps in the server deployment manual",
"where is the code of conduct section located in the onboarding documentation packet",
"what page outlines the schematic for the water filtration system in the facility blueprint",
"find the exact page where the policy changes for the upcoming fiscal year are listed",
"index of software error codes and their corresponding page numbers in the system admin handbook",
"where are the mounting instructions for the sensor units located in the installation booklet",
"find the page number for the summary table of student performance metrics in the academic evaluation report",
"what page has the direct contact list for regional compliance officers in this directory",
"locate the appendix for insurance claim codes and tell me what page it begins on",
"where in the user manual is the section detailing initial battery calibration steps",
"find the page that maps out the organizational hierarchy for the procurement department",
"what page contains the schematic drawings for the turbine assembly",
"index of risk assessment methodologies in the portfolio management guide",
"find the exact page for the software licensing agreement and terms of use",
"where is the index of charts located in the geological survey report",
"what page contains the physical dimensions and weight specifications for the shipping containers",
"locate the page with the step-by-step instructions for resetting the main circuit breaker",
"where is the section on intellectual property rights in the research grant guidelines document",
"find the page number for the comprehensive list of prohibited materials in the shipping manual",
"what page details the emergency evacuation map for the third floor of the office complex",
"index of technical terms used in the semiconductor manufacturing white paper",
"where can I find the specific page for the product recall procedure flowchart",
"look up the page number that contains the detailed breakdown of the quarterly marketing budget",
"find the page that outlines the disclosure requirements for seasonal employees in the policy brief",
"what page contains the structural load-bearing limits for the warehouse shelving units",
"where is the alphabetical index located in the comprehensive medical textbook",
"find the page with the calibration settings for the infrared camera array",
"what page in the vendor contract outlines the late delivery penalty clauses",
"locate the index of maps in the urban planning and zoning manual",
"where is the page that details the configuration parameters for the database synchronization script",
"what page contains the table comparing different encryption algorithms and their performance benchmarks",
"find the page number for the section on student accommodation policies in the university bylaws",
"where is the table of acronyms located in the defense procurement document",
"what page outlines the safety inspection checklist for the overhead cranes",
"locate the index of case studies at the end of the business strategy report",
"where is the page detailing the operational limits for the deep-sea drilling equipment",
"find the exact page for the maintenance schedule of the fleet vehicles",
"what page contains the mathematical proofs for the optimization algorithm described in chapter 3",
"index of tax forms and filing schedules in the corporate accounting handbook",
"where can I find the page listing the ingredients and allergen warnings for the inventory line",
"find the page number that shows the localized distribution map for the public health study",
"what page outlines the multi-factor authentication setup guide for remote employees",
"locate the page with the technical drawings for the pipe valve configuration",
"where is the reference index for regulatory compliance updates in the legal handbook",
"what page details the data retention timeline for user access logs",
"find the page containing the chemical safety data sheet for the industrial solvent",
"where is the index of authors located in the annual research symposium compilation",
"what page shows the network topology diagram for the retail store point-of-sale systems",
"locate the page detailing the reimbursement submission process in the travel policy guide",
"where is the section on hazardous waste disposal protocols located in the lab safety manual",
"what page contains the blueprint for the electrical subpanel wiring",
"find the page number for the cross-reference table of international standards in the auditing guide",
"index of keywords for the cloud architecture design patterns book",
"where is the page that lists the software dependencies for the application deployment patch",
"what page contains the torque specification table for the automotive assembly line",
"locate the page for the internal dispute resolution process in the corporate bylaws",
"where is the index of standard operating procedures in the manufacturing quality assurance binder",
"what page contains the layout diagram for the solar panel array on the roof",
"find the page number that outlines the privacy policy updates for the mobile application",
"where in the document is the page that specifies the allowable tolerances for the CNC machine setup",
"what page details the step-by-step procedure for decommissioning old network hardware",
"locate the index of therapeutic interventions in the clinical nursing manual",
"where is the page showing the historical revenue comparison chart in the investor prospectus",
"what page contains the guidelines for formatting academic citations in the dissertation handbook",
"find the page number for the inventory stock keeping unit listing in the logistics manual",
"where is the section explaining the calibration of the pressure gauges located in the operator guide",
"what page outlines the server failover recovery procedure for the DevOps team",
"locate the page with the formal definition of terms for the procurement contract",
"where is the index of statistical tables located in the census data report",
"what page contains the pinout diagram for the microcontroller interface board",
"find the page number for the employee benefits summary matrix in the HR guide",
"where is the section on compliance auditing for environmental impact located in the corporate charter",
"what page details the quality control testing metrics for the pharmaceutical batch",
"locate the page that outlines the security patching schedule for the enterprise servers",
"where is the index of regulatory filings located in the energy grid management manual",
"what page contains the schematic for the hydraulic brake system assembly",
"find the page number for the student code of conduct in the academic planner",
"where is the section on handling suspicious packages located in the facility security handbook",
"what page outlines the data validation rules for the financial reporting template",
"locate the page with the step-by-step instructions for replacing the main air filter unit",
"where is the index of clinical symptoms located in the diagnostic reference manual",
"what page contains the block diagram for the audio processing subsystem",
"find the page number for the non-disclosure agreement clause in the partnership documentation",
"where is the section detailing the escalation path for high-priority software bugs located in the project plan",
"what page contains the comprehensive index of all subjects covered in this user guide" """,
  
    "GRAPH": """
   "how are these various components interconnected and what is the overarching relationship between them",
"map the influence path from the initial policy change to the ultimate downstream operational impact",
"what is the web of dependencies surrounding this specific process",
"trace the lineage of this concept through the different layers of our system",
"show me the interconnected network of risks associated with this technical failure",
"how does this entity relate to the broader ecosystem of assets",
"what is the cascading effect of changing this parameter on the rest of the network",
"visualize the hierarchy and associative links between these disparate research topics",
"what connects these two seemingly unrelated concepts in our knowledge base",
"provide a structural overview of how these legal entities interact with each other",
"find the path of least resistance through these interconnected functional modules",
"what is the community structure of these actors within the governance model",
"explain the relational ecosystem between these technological nodes",
"trace the origin of these requirements back to their foundational principles",
"how do these various departments influence each other through their shared workflows",
"map the flow of information across these cross-functional teams",
"what are the transitive relationships between these financial assets",
"how does this sub-system integrate into the global infrastructure map",
"identify the key central nodes in this network of documentation",
"what is the associative bond between these two clinical observations",
"show the propagation of security vulnerabilities across these linked applications",
"how do these research findings cluster together based on their underlying citations",
"describe the network topology of these interconnected supply chain nodes",
"what is the holistic connection between these regulatory frameworks and operational compliance",
"trace the evolution of these concepts through their various iterations and connections",
"map the collaborative network of these academic institutions",
"what are the indirect influences that link these two business processes",
"how does the energy distribution network relate to the smart grid control modules",
"identify the network of stakeholders involved in this multi-tiered project",
"what is the relationship structure between these specific manufacturing sub-assemblies",
"visualize the dependency graph of these microservices",
"how do these policy guidelines link back to the core organizational mission",
"find all paths connecting this technical issue to its root cause in the network",
"what is the cluster of topics most closely related to this central theme",
"map the connectivity between these various legislative acts",
"how does this asset interact with the wider portfolio of investments",
"what is the structural relationship between these diverse scientific domains",
"trace the chain of command and information flow through the government agency hierarchy",
"identify the gaps in the connection between these two essential data streams",
"how do these cultural and societal factors intersect with the technological adoption rate",
"provide a relational map of these risk factors and their potential impact",
"what are the common links between these disparate international trade agreements",
"show me the interaction network between these pharmaceutical compounds and biological pathways",
"how does this software component link into the broader legacy system architecture",
"trace the sequence of events that connect these market trends to currency fluctuations",
"what are the overlapping nodes between these two enterprise documentation silos",
"map the influence of these external environmental factors on the energy production network",
"how are these educational modules sequenced and related by knowledge prerequisites",
"what is the network of support for this specific research hypothesis",
"identify the bridge entities that link these two functional silos",
"how do these specific cybersecurity threats propagate through the interconnected network",
"visualize the relationship between these historical events and current policy trends",
"what is the connectivity profile of this node within the overall system graph",
"trace the propagation of a change through this complex system of dependencies",
"how do these different financial indices relate to each other in a global market",
"map the collaborative structure of these research groups",
"what are the semantic connections between these two disparate technical documents",
"how does this specific task integrate into the broader project dependency graph",
"identify the central hubs of information in this professional network",
"what is the relational distance between these two concepts",
"describe the architecture of the interconnected systems and their communication paths",
"how do these individual pieces of legislation form a cohesive legal framework",
"map the flow of resources between these different operational units",
"what are the hidden associations between these customer behaviors",
"visualize the hierarchical links within this organizational structure",
"how does this research domain intersect with existing industrial applications",
"trace the dependency path of these critical infrastructure assets",
"what is the ecosystem of tools surrounding this programming language",
"identify the clusters of related problems within the support ticket graph",
"how do these regional energy policies interlink on a national level",
"what connects these diverse symptoms in a unified diagnostic graph",
"map the evolution of these technologies through their shared innovation roots",
"how do these distinct teams collaborate through shared documentation interfaces",
"trace the causal relationship between these economic factors and industrial growth",
"visualize the network of citations in this field of study",
"what is the connectivity between these remote office locations and the main data center",
"identify the nodes that act as intermediaries between these two process streams",
"how does this policy framework adapt to the interconnected nature of modern digital trade",
"describe the intricate web of relationships within this supply chain",
"what are the recurring patterns of interaction in this network",
"map the interdependencies between these security controls",
"how do these disparate data entities form a unified semantic graph",
"trace the historical connections between these competing philosophies",
"identify the influential nodes that drive the overall network behavior",
"what is the relational mapping of these legal precedents",
"how do these learning outcomes link back to the curriculum structure",
"visualize the dependency network of these critical project milestones",
"what are the connective tissues between these two corporate divisions",
"map the relationship of these small-scale processes to the grand-scale objective",
"how do these technological standards influence the connectivity of global devices",
"trace the chain of impact from this single failure across the whole network",
"identify the shared nodes between these various research initiatives",
"what is the structural graph of these interconnected manufacturing stages",
"how does this specific legal clause connect to the rest of the contract",
"visualize the hierarchy of these scientific classifications",
"what is the interplay between these different financial risk categories",
"map the influence of these pedagogical strategies on student performance clusters",
"how do these independent systems communicate and relate to each other",
"trace the paths of innovation through the collaborative research network",
"identify the global clusters within this vast information space"
    """,

    "AGENTIC": """
    "Investigate the root cause of this issue by reviewing related documents, historical incidents, and dependency records.",
"Create a recommendation based on policies, prior decisions, and supporting documentation across multiple sources.",
"Trace how this requirement evolved over time and summarize the rationale behind each change.",
"Find all documents relevant to this problem, identify contradictions, and propose the most likely conclusion.",
"Determine whether this request complies with applicable guidelines by examining all related references.",
"Analyze the impact of this change across teams, systems, and documented processes.",
"Build a complete answer by gathering evidence from procedures, specifications, and meeting records.",
"What sequence of actions should be taken to resolve this situation based on available documentation?",
"Research this topic across internal knowledge sources and generate a consolidated assessment.",
"Compare recommendations from different documents and explain which guidance should be followed.",
"Identify dependencies that could affect implementation and summarize associated risks.",
"Review historical cases similar to this one and explain how they were resolved.",
"Map the relationships between requirements, controls, and documented exceptions.",
"Determine the best course of action when multiple policies appear to conflict.",
"Investigate why previous attempts failed and identify lessons learned from related records.",
"Gather information from all relevant sources and prepare a decision briefing.",
"Find the authoritative source for this topic and explain how supporting documents align with it.",
"Assess whether existing evidence supports proceeding with this request.",
"Trace the origin of this rule and identify all documents that reference it.",
"Develop a step-by-step resolution plan using information from multiple repositories.",
"Which documents should be consulted before making this decision, and what do they collectively indicate?",
"Review requirements, exceptions, approvals, and historical outcomes before providing guidance.",
"Perform a comprehensive investigation into this issue and summarize findings.",
"Identify unresolved questions after reviewing all available documentation.",
"Determine whether any prior decisions establish a precedent for this situation.",
"Analyze related records to identify patterns that explain the current problem.",
"Cross-reference procedures, standards, and operational guidance to answer this question.",
"Find all evidence supporting and opposing this proposal and synthesize a recommendation.",
"Examine multiple knowledge sources and create a unified explanation.",
"Investigate dependencies, constraints, and exceptions that may influence the outcome.",
"Review documentation across departments and identify areas requiring coordination.",
"What information is missing to confidently answer this question?",
"Evaluate alternative approaches using documented experience and supporting evidence.",
"Search for related incidents, compare resolutions, and recommend next steps.",
"Determine whether this situation has occurred before and what actions were taken.",
"Construct a complete picture of this topic by linking information across sources.",
"Identify all stakeholders, responsibilities, and approvals associated with this process.",
"Review the evidence chain behind this conclusion and verify its validity.",
"Find inconsistencies across documents and explain how they should be resolved.",
"Assess risks, mitigations, and dependencies using available knowledge sources.",
"Research this request thoroughly and prepare an executive summary.",
"Determine which guidance takes precedence when documentation disagrees.",
"Explore related topics that may indirectly affect this decision.",
"Analyze documentation, historical outcomes, and exceptions before answering.",
"Gather context from multiple repositories and explain the broader implications.",
"Identify all relevant references required to support a final recommendation.",
"Review previous investigations and determine whether their conclusions still apply.",
"Provide a reasoned judgment after examining all available evidence.",
"Map the workflow, decision points, and exceptions associated with this scenario.",
"Find supporting documentation, validate assumptions, and identify gaps.",
"Conduct a multi-step analysis to determine the most defensible answer.",
"Review requirements, implementation notes, and operational procedures together.",
"What does the complete body of available knowledge suggest about this issue?",
"Investigate related dependencies before recommending a path forward.",
"Collect evidence from multiple documents and reconcile conflicting information.",
"Determine how changes in one area affect related processes and obligations.",
"Analyze this issue from historical, procedural, and operational perspectives.",
"Identify which conclusions are strongly supported and which remain uncertain.",
"Research the full context behind this request rather than a single document.",
"Compare documented guidance with actual historical outcomes.",
"Review all relevant sources and explain the reasoning behind your recommendation.",
"Determine whether there are hidden dependencies that could alter the decision.",
"Trace references across documents until the original source is identified.",
"Investigate exceptions, edge cases, and special circumstances related to this topic.",
"Find every document contributing to this requirement and summarize their roles.",
"Synthesize information from policies, procedures, and past cases.",
"Assess the strength of available evidence before drawing a conclusion.",
"Review cross-functional documentation to understand end-to-end implications.",
"Determine whether this recommendation aligns with established precedent.",
"Search broadly, evaluate findings, and produce a final decision rationale.",
"Identify the chain of reasoning required to answer this question accurately.",
"Investigate this topic as if preparing a formal review for decision makers.",
"Find all related materials, analyze them, and explain what action should be taken.",
"Review documentation iteratively until a complete answer can be constructed.",
"Determine whether any conflicting guidance exists and how it should be interpreted.",
"Analyze dependencies between requirements, controls, and implementation details.",
"Research historical context before evaluating current recommendations.",
"Identify supporting evidence for each major claim related to this issue.",
"Develop a comprehensive understanding by traversing linked documents and references.",
"Review prior approvals, exceptions, and decisions before making a recommendation.",
"Assess whether current guidance remains consistent across all sources.",
"Investigate root causes by following references through related records.",
"Construct an evidence-backed recommendation from distributed knowledge sources.",
"Find and reconcile discrepancies across documentation sets.",
"Evaluate this issue using both documented rules and historical practice.",
"Determine the most reliable answer after comparing multiple sources of truth.",
"Research dependencies and downstream effects before proposing a solution.",
"Review all connected topics that could influence the final outcome.",
"Perform a deep knowledge search and synthesize findings into a coherent conclusion.",
"Identify what additional information must be gathered to reduce uncertainty.",
"Analyze relationships among documents, decisions, and operational outcomes.",
"Gather evidence iteratively until the question can be answered confidently.",
"Determine whether historical precedent overrides general guidance in this case.",
"Review all available context, validate assumptions, and recommend next actions.",
"Investigate this request from multiple angles before reaching a conclusion.",
"Build a complete decision package by combining information from numerous sources.",
"Find relevant evidence, evaluate credibility, resolve conflicts, and provide guidance.",
"Perform an end-to-end investigation and generate a justified recommendation."
    """
}
